# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Semi-Parametric Bayesian Logistic Regression Capture-Recapture
#' 
#' This function computes MCMC samples of N using the the Bayesian Logistic
#' Regression Capture-Recapture model.
#' 
#' @param y a nxJ matrix of capture patterns.
#' @param x a nxH matrix of covariates.
#' @param priorb a (H+1) vector of prior means for the coefficients
#' @param priorB a (H+1)x(H+1) covariance matrix for the coefficients
#' @param priorMU0 a Hx1 vector of prior covariate means. Default=(0,...,0).
#' @param priorlambda0 a HxH prior covariance matrix for the covariates
#' @param priorkappa0 a positve real value
#' @param priornu0 a positive real value
#' @param aalpha a positive real value
#' @param balpha a positive real value
#' @param Kstar an integer of maximum number of mixture classes
#' @param samples the number of MCMC samples to draw from the posterior
#' 
#' @return List with components "N" and "beta". 
#' \describe{
#' \item{"N"}{is a single estimate of the population size.}
#' \item{"beta"}{is a matrix of beta estimates.}
#' }
#' 
#' @examples
#' #Generate the Data
#' mybeta = matrix(c(-2,-1,1,
#'                   -2,1,-1,
#'                   -2,-1,1,
#'                   -2,1,-1),nrow=4,byrow=TRUE)
#'                   
#' mynormprobs=c(0.3,0.4,0.3)
#' 
#' mynormmeans=matrix(c(2,2,
#'                      0,0,
#'                      -2,-2),ncol=2,byrow=TRUE)
#'                      
#' mynormsigma=matrix(c(.5,.45,.45,.5,
#'                       1,0,0,1,
#'                       .5,-.35,-.35,.5),nrow=3,byrow=TRUE)
#' 
#' mydata = multdatasimulator(2000,mybeta,mynormprobs,mynormmeans,mynormsigma,
#'                            missing="yes")
#'                            
#' #Run the Algorithm
#' mypriorb=rep(0,3) #prior on intercept and both beta means set to 0
#' mypriorB=diag(3) #identity matrix, size 3     
#' 
#' condBLRCRsolver(as.matrix(mydata[,1:4]),
#'                 as.matrix(mydata[,5:6]),mypriorb,mypriorB)                      
#' 
#' @export 
SPBLRCRsolver <- function(y, x, priorb, priorB, priorMU0, priorlambda0, priorkappa0 = 1, priornu0 = 1, aalpha = 0.25, balpha = 0.25, Kstar = 10L, samples = 1000L) {
    .Call(`_BLRCR_SPBLRCRsolver`, y, x, priorb, priorB, priorMU0, priorlambda0, priorkappa0, priornu0, aalpha, balpha, Kstar, samples)
}

#' Bayesian Logistic Regression Capture-Recapture using Conditional Likelihood
#' 
#' This function computes the Bayesian Logistic Regression Capture-Recapture estimate for N
#' using the conditional maximum likelihood (instead of the full likelihood).
#' 
#' @param y a nxj matrix of capture patterns.
#' @param x a nxh matrix of covariates.
#' @param priorb a (h+1) vector of prior means for the coefficients
#' @param priorB a (h+1)x(h+1) covariance matrix for the coefficients
#' 
#' @return List with components "N" and "beta". 
#' \describe{
#' \item{"N"}{is a single estimate of the population size.}
#' \item{"beta"}{is a matrix of beta estimates.}
#' }
#' 
#' @examples
#' #Generate the Data
#' mybeta = matrix(c(-2,-1,1,
#'                   -2,1,-1,
#'                   -2,-1,1,
#'                   -2,1,-1),nrow=4,byrow=TRUE)
#'                   
#' mynormprobs=c(0.3,0.4,0.3)
#' 
#' mynormmeans=matrix(c(2,2,
#'                      0,0,
#'                      -2,-2),ncol=2,byrow=TRUE)
#'                      
#' mynormsigma=matrix(c(.5,.45,.45,.5,
#'                       1,0,0,1,
#'                       .5,-.35,-.35,.5),nrow=3,byrow=TRUE)
#' 
#' mydata = multdatasimulator(2000,mybeta,mynormprobs,mynormmeans,mynormsigma,
#'                            missing="yes")
#'                            
#' #Run the Algorithm
#' mypriorb=rep(0,3) #prior on intercept and both beta means set to 0
#' mypriorB=diag(3) #identity matrix, size 3     
#' 
#' condBLRCRsolver(as.matrix(mydata[,1:4]),
#'                 as.matrix(mydata[,5:6]),mypriorb,mypriorB)                      
#' 
#' @export 
condBLRCRsolver <- function(y, x, priorb, priorB, gradparam = 0.01, prior = 1L, tol = 1e-6, maxiter = 1000L) {
    .Call(`_BLRCR_condBLRCRsolver`, y, x, priorb, priorB, gradparam, prior, tol, maxiter)
}

